apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
data:
  config.yml: |
    domain: {{ .Values.exposeController.domain }}
    exposer: Ingress
    {{- if .Values.exposeController.urltemplate }}
    urltemplate: "{{ .Values.exposeController.urltemplate }}"
    {{- end }}
    {{- if .Values.exposeController.http }}
    http: {{ .Values.exposeController.http }}
    {{- end }}