apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: {{ template "name" . }}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: {{ template "name" . }}
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.exposeController.image.name }}:{{ .Values.exposeController.image.tag }}"
        imagePullPolicy: {{ .Values.exposeController.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/restarteveryday
          initialDelaySeconds: {{ .Values.exposeController.probes.liveness.initialDelaySeconds }}
        name: {{ template "name" . }}
        volumeMounts:
        - mountPath: /etc/exposecontroller
          name: config-volume
      serviceAccountName: {{ template "name" . }}
      volumes:
      - configMap:
          name: {{ template "name" . }}
        name: config-volume