apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "name" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "name" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: {{ template "name" . }}
      labels:
        app: {{ template "name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.exposeController.image.name }}:{{ .Values.exposeController.image.tag }}"
        imagePullPolicy: {{ .Values.exposeController.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/restarteveryday
          initialDelaySeconds: 86164
        name: {{ template "name" . }}
        volumeMounts:
        - mountPath: /etc/exposecontroller
          name: config-volume
      serviceAccountName: {{template "name" . }}-ns-fabric8
      volumes:
      - configMap:
          name: {{ template "name" . }}
        name: config-volume