# one Role gives access to services, ingresses & configmaps in the same namespace as the exposecontroller is running
# other Role gives access to the services in the default namespace

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name" . }}-ns-{{ .Values.exposeController.namespace }}
  namespace: {{ .Values.exposeController.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "name" . }}-{{ .Values.exposeController.namespace }}-role
  namespace: {{ .Values.exposeController.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - list
      - get
      - update
      - patch
      - watch
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "name" . }}-{{ .Values.exposeController.namespace }}-role-binding
  namespace: {{ .Values.exposeController.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "name" . }}-{{ .Values.exposeController.namespace }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}-ns-{{ .Values.exposeController.namespace }}
    namespace: {{ .Values.exposeController.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "name" . }}-default-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "name" . }}-default-role-binding
  # This only grants permissions within the "default" namespace.
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "name" . }}-default-role
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}-ns-{{ .Values.exposeController.namespace }}
    namespace: {{ .Values.exposeController.namespace }}