---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "exposecontroller.name" . }}-{{ .Release.Namespace }}-default-role
  labels:
{{ include "exposecontroller.labels.stakater" . | indent 4 }}
{{ include "exposecontroller.labels.chart" . | indent 4 }}
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "exposecontroller.name" . }}-{{ .Release.Namespace }}-default-role-binding
  labels:
{{ include "exposecontroller.labels.stakater" . | indent 4 }}
{{ include "exposecontroller.labels.chart" . | indent 4 }}
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "exposecontroller.name" . }}-{{ .Release.Namespace }}-default-role
subjects:
  - kind: ServiceAccount
    name: {{ template "exposecontroller.name" . }}
    namespace: {{ .Release.Namespace }}