---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "name" . }}-{{ .Values.exposeController.namespace }}-default-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "name" . }}-{{ .Values.exposeController.namespace }}-default-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "name" . }}-{{ .Values.exposeController.namespace }}-default-role
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}
    namespace: {{ .Values.exposeController.namespace }}