---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "exposecontroller.name" . }}-{{ .Release.Namespace }}-role
  labels:
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}
rules:
  {{- if .Values.exposeController.isOpenShift }}
  - apiGroups:
      - ""
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
  {{- end }}
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "exposecontroller.name" . }}-{{ .Release.Namespace }}-role-binding
  labels:
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "exposecontroller.name" . }}-{{ .Release.Namespace }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "exposecontroller.name" . }}
    namespace: {{ .Release.Namespace }}