apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "exposecontroller.name" . }}
  labels:
{{ include "kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "kube-state-metrics.labels.chart" . | indent 4 }}