exposeController:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 2.3.56
  domain: stackator.com 
  exposer: Ingress
  isOpenShift: false
  # nodeSelector:
  #   key: failure-domain.beta.kubernetes.io/zone
  #   value: us-west-2a
  # false by default
#  http: true
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 400Mi
      cpu: 400m
  probes:
    liveness:
      initialDelaySeconds: 86164
  image:
    name: jenkinsxio/exposecontroller
    tag: "2.3.56"
    pullPolicy: IfNotPresent